import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: "Search Events & Organisations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mt-6 mx-[30px] bg-[#F5F5F5]">
        <Header />
        {children}
      </body>
    </html>
  );
}
